config/routes.rb
Rails.application.routes.draw do
  resources :courier_statuses
  resources :couriers
  resources :product_orders
  resources :orders
  resources :order_statuses
  resources :products
  resources :customers
  resources :restaurants
  resources :employees
  resources :addresses
  devise_for :users

  root to: "home#index"

  # GET routes
  get '/users', to: 'users#index'
  get 'products', to: 'products#index'

  namespace :api do
    get '/orders', to: 'orders#index', as: 'api_orders'
    post 'login', to: 'auth#index'

    resources :orders, only: [:index, :create] do
      namespace :api do
        post '/api/order/#{@order.id}/status', to: 'orders#update_order_status', as: 'api_update_order_status'
      end
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
    has_many :employees
    has_many :customers
    has_one :restaurant
    has_many :couriers
    validates :street_address, :city, :postal_code, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/courier.rb
class Courier < ApplicationRecord
belongs_to :user
belongs_to :address
belongs_to :courier_status
has_many :orders
validates :user_id, :address_id, :courier_status_id, :phone, :active, presence: true
end

app/models/courier_status.rb
class CourierStatus < ApplicationRecord
    has_many :couriers
    validates :name,  presence:true
end

app/models/customer.rb
class Customer < ApplicationRecord
    validates_uniqueness_of :user_id
    validates :phone, :address_id, :active, :user_id, presence: true
    belongs_to :address
    belongs_to :user
    has_many :orders

end

app/models/employee.rb
class Employee < ApplicationRecord
    validates_uniqueness_of :user_id 
    validates :address_id, :user_id, :phone, presence: true
    belongs_to :user
    belongs_to :address
    
    
end

app/models/order.rb
class Order < ApplicationRecord

    validates :restaurant_rating, :inclusion => { :in => 1..5 }, allow_nil: true
    validates :restaurant_id, :customer_id, :order_status_id, presence: true
    belongs_to :restaurant
    belongs_to :customer
    belongs_to :order_status
    belongs_to :courier, optional: true
    has_many :product_orders
    
end
def self.user_orders(user_type, id)
    # ... your implementation logic here
  end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
    validates :name, presence: true
    has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :restaurant
    has_many :product_orders
    validates :restaurant_id, :name, :cost, presence: true
    validates :cost, :numericality => { greater_than_or_equal_to: 0 } 

end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
    belongs_to :order
    belongs_to :product
    validates :product_quantity, :numericality => { greater_than: 0 } 
    validates :product_unit_cost, :numericality => { greater_than_or_equal_to: 0 }
    validates :product_id, :order_id, :product_quantity, :product_unit_cost, presence:true
    validates :product_id, uniqueness: {scope: :order_id}
    validate :product_belongs_to_restaurant

    def product_belongs_to_restaurant
        if product.present? && order.present? && product.restaurant_id != order.restaurant_id
            errors.add(:product, "must belong to the same restaurant as the order")
        end
    end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    validates_uniqueness_of :address_id
    validates :price_range, :inclusion => { :in => 1..3 }
    validates :user, :phone, :price_range, :address, :name, :active, presence: true
    belongs_to :user, class_name: 'User', foreign_key: 'user_id'
    belongs_to :address, class_name: 'Address', foreign_key: 'address_id'
    has_many :products
    has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable 
  devise  :database_authenticatable, 
          :registerable,
          :recoverable, 
          :rememberable, 
          :validatable

  has_one :employee
  has_one :customer
  has_many :restaurants
  has_one :courier
  validates :name, :password, presence: true

end
  def authenticate(password)
    if BCrypt::Password.new(self.password_digest).is_password?(password)
      return self
    else
      return false
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
      render
    end
  end

app/controllers/product_orders_controller.rb
class ProductOrdersController < ApplicationController
  before_action :set_product_order, only: %i[ show edit update destroy ]

  # GET /product_orders or /product_orders.json
  def index
    @product_orders = ProductOrder.all
  end

  # GET /product_orders/1 or /product_orders/1.json
  def show
  end

  # GET /product_orders/new
  def new
    @product_order = ProductOrder.new
  end

  # GET /product_orders/1/edit
  def edit
  end

  # POST /product_orders or /product_orders.json
  def create
    @product_order = ProductOrder.new(product_order_params)

    respond_to do |format|
      if @product_order.save
        format.html { redirect_to product_order_url(@product_order), notice: "Product order was successfully created." }
        format.json { render :show, status: :created, location: @product_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_orders/1 or /product_orders/1.json
  def update
    respond_to do |format|
      if @product_order.update(product_order_params)
        format.html { redirect_to product_order_url(@product_order), notice: "Product order was successfully updated." }
        format.json { render :show, status: :ok, location: @product_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_orders/1 or /product_orders/1.json
  def destroy
    @product_order.destroy

    respond_to do |format|
      format.html { redirect_to product_orders_url, notice: "Product order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_order
      @product_order = ProductOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_order_params
      params.require(:product_order).permit(:product_id, :order_id, :product_quatity, :product_unit_cost)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/couriers_helper.rb
module CouriersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_orders_helper.rb
module ProductOrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/product_orders/_form.html.erb
<%= form_with(model: product_order) do |form| %>
  <% if product_order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product_order.errors.count, "error") %> prohibited this product_order from being saved:</h2>

      <ul>
        <% product_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.number_field :product_id %>
  </div>

  <div>
    <%= form.label :order_id, style: "display: block" %>
    <%= form.number_field :order_id %>
  </div>

  <div>
    <%= form.label :product_quatity, style: "display: block" %>
    <%= form.number_field :product_quatity %>
  </div>

  <div>
    <%= form.label :product_unit_cost, style: "display: block" %>
    <%= form.number_field :product_unit_cost %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/product_orders/_product_order.html.erb
<div id="<%= dom_id product_order %>">
  <p>
    <strong>Product:</strong>
    <%= product_order.product_id %>
  </p>

  <p>
    <strong>Order:</strong>
    <%= product_order.order_id %>
  </p>

  <p>
    <strong>Product quatity:</strong>
    <%= product_order.product_quatity %>
  </p>

  <p>
    <strong>Product unit cost:</strong>
    <%= product_order.product_unit_cost %>
  </p>

</div>

app/views/product_orders/edit.html.erb
<h1>Editing product order</h1>

<%= render "form", product_order: @product_order %>

<br>

<div>
  <%= link_to "Show this product order", @product_order %> |
  <%= link_to "Back to product orders", product_orders_path %>
</div>

app/views/product_orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Product orders</h1>

<div id="product_orders">
  <% @product_orders.each do |product_order| %>
    <%= render product_order %>
    <p>
      <%= link_to "Show this product order", product_order %>
    </p>
  <% end %>
</div>

<%= link_to "New product order", new_product_order_path %>

app/views/product_orders/new.html.erb
<h1>New product order</h1>

<%= render "form", product_order: @product_order %>

<br>

<div>
  <%= link_to "Back to product orders", product_orders_path %>
</div>

app/views/product_orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product_order %>

<div>
  <%= link_to "Edit this product order", edit_product_order_path(@product_order) %> |
  <%= link_to "Back to product orders", product_orders_path %>

  <%= button_to "Destroy this product order", @product_order, method: :delete %>
</div>