config/routes.rb
Rails.application.routes.draw do
  resources :courier_statuses
  resources :couriers
  resources :product_orders
  resources :orders
  resources :order_statuses
  resources :products
  resources :customers
  resources :restaurants
  resources :employees
  resources :addresses
  devise_for :users

  root to: "home#index"

  # GET routes
  get '/users', to: 'users#index'
  get 'products', to: 'products#index'

  namespace :api do
    get '/orders', to: 'orders#index', as: 'api_orders'
    post 'login', to: 'auth#index'

    resources :orders, only: [:index, :create] do
      namespace :api do
        post '/api/order/#{@order.id}/status', to: 'orders#update_order_status', as: 'api_update_order_status'
      end
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
    has_many :employees
    has_many :customers
    has_one :restaurant
    has_many :couriers
    validates :street_address, :city, :postal_code, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/courier.rb
class Courier < ApplicationRecord
belongs_to :user
belongs_to :address
belongs_to :courier_status
has_many :orders
validates :user_id, :address_id, :courier_status_id, :phone, :active, presence: true
end

app/models/courier_status.rb
class CourierStatus < ApplicationRecord
    has_many :couriers
    validates :name,  presence:true
end

app/models/customer.rb
class Customer < ApplicationRecord
    validates_uniqueness_of :user_id
    validates :phone, :address_id, :active, :user_id, presence: true
    belongs_to :address
    belongs_to :user
    has_many :orders

end

app/models/employee.rb
class Employee < ApplicationRecord
    validates_uniqueness_of :user_id 
    validates :address_id, :user_id, :phone, presence: true
    belongs_to :user
    belongs_to :address
    
    
end

app/models/order.rb
class Order < ApplicationRecord

    validates :restaurant_rating, :inclusion => { :in => 1..5 }, allow_nil: true
    validates :restaurant_id, :customer_id, :order_status_id, presence: true
    belongs_to :restaurant
    belongs_to :customer
    belongs_to :order_status
    belongs_to :courier, optional: true
    has_many :product_orders
    
end
def self.user_orders(user_type, id)
    # ... your implementation logic here
  end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
    validates :name, presence: true
    has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :restaurant
    has_many :product_orders
    validates :restaurant_id, :name, :cost, presence: true
    validates :cost, :numericality => { greater_than_or_equal_to: 0 } 

end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
    belongs_to :order
    belongs_to :product
    validates :product_quantity, :numericality => { greater_than: 0 } 
    validates :product_unit_cost, :numericality => { greater_than_or_equal_to: 0 }
    validates :product_id, :order_id, :product_quantity, :product_unit_cost, presence:true
    validates :product_id, uniqueness: {scope: :order_id}
    validate :product_belongs_to_restaurant

    def product_belongs_to_restaurant
        if product.present? && order.present? && product.restaurant_id != order.restaurant_id
            errors.add(:product, "must belong to the same restaurant as the order")
        end
    end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    validates_uniqueness_of :address_id
    validates :price_range, :inclusion => { :in => 1..3 }
    validates :user, :phone, :price_range, :address, :name, :active, presence: true
    belongs_to :user, class_name: 'User', foreign_key: 'user_id'
    belongs_to :address, class_name: 'Address', foreign_key: 'address_id'
    has_many :products
    has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable 
  devise  :database_authenticatable, 
          :registerable,
          :recoverable, 
          :rememberable, 
          :validatable

  has_one :employee
  has_one :customer
  has_many :restaurants
  has_one :courier
  validates :name, :password, presence: true

end
  def authenticate(password)
    if BCrypt::Password.new(self.password_digest).is_password?(password)
      return self
    else
      return false
    end
  end

app/controllers/courier_statuses_controller.rb
class CourierStatusesController < ApplicationController
  before_action :set_courier_status, only: %i[ show edit update destroy ]

  # GET /courier_statuses or /courier_statuses.json
  def index
    @courier_statuses = CourierStatus.all
  end

  # GET /courier_statuses/1 or /courier_statuses/1.json
  def show
  end

  # GET /courier_statuses/new
  def new
    @courier_status = CourierStatus.new
  end

  # GET /courier_statuses/1/edit
  def edit
  end

  # POST /courier_statuses or /courier_statuses.json
  def create
    @courier_status = CourierStatus.new(courier_status_params)

    respond_to do |format|
      if @courier_status.save
        format.html { redirect_to courier_status_url(@courier_status), notice: "Courier status was successfully created." }
        format.json { render :show, status: :created, location: @courier_status }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @courier_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courier_statuses/1 or /courier_statuses/1.json
  def update
    respond_to do |format|
      if @courier_status.update(courier_status_params)
        format.html { redirect_to courier_status_url(@courier_status), notice: "Courier status was successfully updated." }
        format.json { render :show, status: :ok, location: @courier_status }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @courier_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courier_statuses/1 or /courier_statuses/1.json
  def destroy
    @courier_status.destroy

    respond_to do |format|
      format.html { redirect_to courier_statuses_url, notice: "Courier status was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_courier_status
      @courier_status = CourierStatus.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def courier_status_params
      params.require(:courier_status).permit(:name)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courier_statuses_helper.rb
module CourierStatusesHelper
end

app/helpers/couriers_helper.rb
module CouriersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/courier_statuses/_courier_status.html.erb
<div id="<%= dom_id courier_status %>">
  <p>
    <strong>Name:</strong>
    <%= courier_status.name %>
  </p>

</div>

app/views/courier_statuses/_form.html.erb
<%= form_with(model: courier_status) do |form| %>
  <% if courier_status.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(courier_status.errors.count, "error") %> prohibited this courier_status from being saved:</h2>

      <ul>
        <% courier_status.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courier_statuses/edit.html.erb
<h1>Editing courier status</h1>

<%= render "form", courier_status: @courier_status %>

<br>

<div>
  <%= link_to "Show this courier status", @courier_status %> |
  <%= link_to "Back to courier statuses", courier_statuses_path %>
</div>

app/views/courier_statuses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Courier statuses</h1>

<div id="courier_statuses">
  <% @courier_statuses.each do |courier_status| %>
    <%= render courier_status %>
    <p>
      <%= link_to "Show this courier status", courier_status %>
    </p>
  <% end %>
</div>

<%= link_to "New courier status", new_courier_status_path %>

app/views/courier_statuses/new.html.erb
<h1>New courier status</h1>

<%= render "form", courier_status: @courier_status %>

<br>

<div>
  <%= link_to "Back to courier statuses", courier_statuses_path %>
</div>

app/views/courier_statuses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @courier_status %>

<div>
  <%= link_to "Edit this courier status", edit_courier_status_path(@courier_status) %> |
  <%= link_to "Back to courier statuses", courier_statuses_path %>

  <%= button_to "Destroy this courier status", @courier_status, method: :delete %>
</div>